version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: fabric_db
      MYSQL_ROOT_PASSWORD: 2025
    ports:
      - "3306:3306"
    networks:
      - spring-network

  fabricweb:
    build: .
    container_name: fabric-app
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fabric_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 2025
    ports:
      - "8080:8080"
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge
